name: wavepilot
channels:
  - pytorch 
  - conda-forge
  - nodefaults 
dependencies:
  - python=3.10.13
  - numpy=1.26.4
  - scipy=1.13.0
  - plotly=5.24.1
  - pandas=2.2.3
  - scikit-learn=1.4.1.post1
  - flask=3.0.2
  - flask-socketio=5.3.6
  - optuna=3.6.1
  - pytest=8.2.1
  - pylint=3.1.0
  - python-sounddevice=0.4.6
  - pytorch::pytorch=2.2.1     
  - pytorch::torchvision=0.17.1
  - pytorch::torchaudio=2.2.1
  - pip=24.0
  - pip:
    - python-osc==1.8.3
    - python-reapy==0.10.0
    - torchviz==0.0.2